import Head from 'next/head'

import Navbar from '../../components/Navbar'
import Main from '../../components/Main'
import About from '../../components/About'
import Skills from '../../components/Skills'
import Contacts from '../../components/Contacts'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ova Ferdinan Marbun</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Skills />
      <Contacts />
    </div>
  )
}
